channel_sources:
  # source:
  # - https://conda-forge.org/docs/maintainer/knowledge_base.html#rust-nightly
  # - https://anaconda.org/conda-forge/cython
  # Note: cython version 3.0.0b1 is available under cython_dev label
  # - see here: https://anaconda.org/conda-forge/cython/files?page=2
  - conda-forge/label/cython_dev,conda-forge
