{% set name = "clickhouse-connect" %}
{% set version = "0.5.20" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/clickhouse-connect-{{ version }}.tar.gz
  sha256: 5fc9a84849f3c3b6f6928b45a0df17fa63ebcf4e518b3a48ec70720957e18683

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - setuptools
    - cython ==3.0.0b1
    - pip
  run:
    - python >=3.7
    - certifi
    - urllib3 >=1.26
    - pytz
    - zstandard
    - lz4

test:
  imports:
    - clickhouse_connect
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ClickHouse/clickhouse-connect
  summary: ClickHouse core driver, SqlAlchemy, and Superset libraries
  license: Apache-2.0
  license_file: LICENSE
  description: |
    A suite of Python packages for connecting Python to ClickHouse:

    - Pandas DataFrames
    - Numpy Arrays
    - PyArrow Tables
    - SQLAlchemy 1.3 and 1.4 (limited feature set)
    - Apache Superset 1.4+

    PyPI: [https://pypi.org/project/clickhouse-connect/](https://pypi.org/project/clickhouse-connect/)

    ---

    :fire: The conda-forge recipe was generated with [Conda-Forger App](https://sugatoray-conda-forger.streamlit.app/).

    :point_right: [![Streamlit App](https://static.streamlit.io/badges/streamlit_badge_black_white.svg)](https://sugatoray-conda-forger.streamlit.app/)

    [_streamlit-conda-forger-app]: https://sugatoray-conda-forger.streamlit.app/

  dev_url: https://github.com/ClickHouse/clickhouse-connect
  doc_url: https://clickhouse.com/docs/en/integrations/language-clients/python/intro

extra:
  recipe-maintainers:
    - sugatoray
