{% set name = "clickhouse-connect" %}
{% set version = "0.5.24" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f1c6a4a20c19612eedaf1cea82e532010942cb08a29326db74cce0ea48bbe56d


build:
  entry_points:
    - sqlalchemy.dialects.clickhousedb.connect = clickhouse_connect.cc_sqlalchemy.dialect:ClickHouseDialect
    - sqlalchemy.dialects.clickhousedb = clickhouse_connect.cc_sqlalchemy.dialect:ClickHouseDialect
    - superset.db_engine_specs.clickhousedb = clickhouse_connect.cc_superset.engine:ClickHouseEngineSpec
  number: 0
  script: {{ PYTHON }} setup.py build_ext --inplace && {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  skip: true # [py<37]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cross-python_{{ target_platform }}      # [build_platform != target_platform]
  host:
    - python
    - cython ==3.0.0b1
    - pip
  run:
    - python
    - certifi
    - urllib3 >=1.26
    - pytz
    - zstandard
    - lz4
  run_constrained:
    - sqlalchemy >1.3.21,<1.4
    - apache_superset >=1.4.1
    - pandas
    - pyarrow
    - orjson

test:
  imports:
    - clickhouse_connect
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ClickHouse/clickhouse-connect
  summary: ClickHouse core driver, SqlAlchemy, and Superset libraries
  license: Apache-2.0
  license_file: LICENSE
  description: |
    A suite of Python packages for connecting Python to ClickHouse:

    - Pandas DataFrames
    - Numpy Arrays
    - PyArrow Tables
    - SQLAlchemy 1.3 and 1.4 (limited feature set)
    - Apache Superset 1.4+

    PyPI: [https://pypi.org/project/clickhouse-connect/](https://pypi.org/project/clickhouse-connect/)

    ---

    :fire: The conda-forge recipe was generated with [Conda-Forger App](https://sugatoray-conda-forger.streamlit.app/).

    :point_right: [![Streamlit App](https://static.streamlit.io/badges/streamlit_badge_black_white.svg)](https://sugatoray-conda-forger.streamlit.app/)

    [_streamlit-conda-forger-app]: https://sugatoray-conda-forger.streamlit.app/

  dev_url: https://github.com/ClickHouse/clickhouse-connect
  doc_url: https://clickhouse.com/docs/en/integrations/language-clients/python/intro

extra:
  recipe-maintainers:
    - sugatoray
